name: CI/CD - democyber

# Déclenche le workflow sur push ou PR vers main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/democyber:latest

    steps:
      # 1️⃣ Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3️⃣ Compile Java code
      - name: Compile Java
        run: mvn compile

      # 3️⃣ Build Maven
      - name: Build Java project with Maven
        run: mvn clean package

      # 4️⃣ Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE_NAME .

      # 6️⃣ Test rapide Docker image
      - name: Test Docker image locally
        run: |
          docker run -d --name democyber-test -p 8080:8080 $DOCKER_IMAGE_NAME
          sleep 10
          curl -f http://localhost:8080 || echo "App not responding"
          docker stop democyber-test
          docker rm democyber-test

      # # 7️⃣ Push Docker image sur Docker Hub
      # - name: Push Docker image
      #   run: docker push $DOCKER_IMAGE_NAME
